import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToasterProvider from "@/components/ToasterProvider";
import Navbar from "@/components/Navbar";
import GlobalPriceTicker from "@/components/GlobalPriceTicker";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-screen flex-col">
        <ToasterProvider />

        <div className="sticky top-0 z-50 bg-white">
          <div className="relative z-30">
            <Navbar />
          </div>

          <div className="relative z-10">
            <GlobalPriceTicker />
          </div>
        </div>

        <div className="flex flex-1 flex-col">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
